name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Flatten charts directory
        env:
          CHARTS: charts/consul charts/consul-backup-gcs/consul-backup-gcs charts/gcloud-cron/gcloud-cron charts/vault/incubator/vault charts/basisai/consul-esm charts/basisai/telegraf charts/fluent-bit/stable/fluent-bit charts/kube-janitor charts/bulldozer-deployment/bulldozer-bot charts/eks-container-insights/eks-container-insights charts/gcp-billing-slack-notify/gcp-billing-slack-notify charts/cert-manager-aio/cert-manager-aio charts/basisai/default-psp charts/basisai/cloudsql-proxy
          CHARTS_DIR: flatten_charts
        run: |
          git checkout --detach
          mkdir $CHARTS_DIR
          cp -r $CHARTS $CHARTS_DIR
          ls -al $CHARTS_DIR
          git add .
          git commit -m "flatten-charts"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-rc.2
        with:
          # chart-releaser version https://github.com/helm/chart-releaser/releases
          version: v1.0.0-beta.1
          charts_dir: flatten_charts
          charts_repo_url: https://charts.amoy.ai
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
